config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  namespace :admin do
    root "static_pages#index"
    resources :reviews
    resources :users
    resources :tours
  end
  resources :tours do
    resources :comments
  end
  resources :book_tours
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
      if user.admin?
        can :manage, :all
      else
        can :read, [User, Tour]
        can :update, User, id: user.id
        can [:create, :read], [BookTour, Comment, Rating]
        can :destory, Comment do |comment|
          comment.user == user
        end
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :tour
  belongs_to :user

  validate :check_valid_tour

  def check_valid_tour
    if quantity == nil
      errors.add(:quantity, Settings.book_tour.quantity_nil)
    elsif sum_quantity < quantity
      errors.add(:quantity, quantity.to_s + Settings.book_tour.quantity_cant)
    end
  end

  def sum_quantity
    tour.quantity - tour.book_tours.sum(:quantity)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tours
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  scope :newest, ->{order :created_at}
  delegate :name, to: :user
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_and_belongs_to_many :tours
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :tour
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_and_belongs_to_many :hotels
  belongs_to :category
  has_many :ratings
  has_many :comments
  has_many :book_tours

  scope :destination_tour,
    ->{where category_id: Settings.admin.destination_tour}
  scope :newest, ->{order :created_at}
  scope :order_name, ->{order :name}
end

app/models/tours_hotel.rb
class ToursHotel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :book_tours
  enum role: {user: 0, admin: 1}
  enum gender: {male: 0, female: 1}

  scope :newest, ->{order :created_at}
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::BaseController
  def index
    @search = Comment.includes(:user).joins(:user).ransack params[:q]
    @reviews = @search.result.newest.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController
  def index; end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  def index
    @tours = Tour.destination_tour.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @search = User.ransack params[:q]
    @users = @search.result.newest.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:name, :date_of_birth, :gender, :address, :phone])
  end
end

app/controllers/book_tours_controller.rb
class BookToursController < ApplicationController
  before_action :load_tour, only: :show
  before_action :load_tour_for_create, only: :create

  def create
    @book_tour = BookTour.new tour_params
    if @book_tour.save
      flash[:success] = t "messenger.success_tour"
      redirect_to tours_path
    else
      flash[:danger] = t "messenger.book_fails"
      render :template => "book_tours/show"
    end
  end

  def show
    @book_tour = BookTour.new
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    redirect_to tours_path
  end

  def load_tour_for_create
    @tour = Tour.find_by id: params[:book_tour][:tour_id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    redirect_to tours_path
  end

  def tour_params
    params.require(:book_tour).permit :user_id, :tour_id, :quantity,
      :price, :note
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_comment, only: :destroy

  def create
    @comment = Comment.new comment_params
    if @comment.save
      flash[:success] = t "comment.successful"
      redirect_to tour_path @comment.tour_id
    else
      flash[:danger] = t "comment.fails"
      redirect_to tour_path @comment.tour_id
    end
  end

  def destroy
    if @comment.destroy
      flash[:success] = t "comment.delete"
      redirect_to tour_path @comment.tour_id
    else
      flash[:danger] = t "comment.fails"
      redirect_to tour_path @comment.tour_id
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content, :user_id, :tour_id
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    return if @comment
    flash[:danger] = t "messenger.no_data"
    redirect_to tour_path @comment.tour_id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @search = Tour.ransack params[:q]
    @tours = @search.result.order_name.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :load_tour, only: %i(show load_status)
  authorize_resource

  def index
    @search = Tour.ransack params[:q]
    @tours = @search.result.newest.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end

  def show
    @status = load_status
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_status
    quantity = @tour.book_tours.sum :quantity
    @tour.quantity - quantity
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(show edit update)

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.gender = params[:gender].to_i
    if @user.save
      log_in @user
      flash[:success] = t "welcome"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @user.gender = params[:gender].to_i
    if @user.update_attributes user_params
      flash[:success] = t "user.update"
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "messenger.no_data"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit :name, :email, :date_of_birth,
      :address, :phone, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include TourHelper
  def full_title page_title
    base_title = I18n.t "framgia.base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/tour_helper.rb
module TourHelper
  def route content
    return if content.length <= Settings.tour.length_small
    truncate content, length: Settings.tour.length_big
  end
end

app/helpers/users_helper.rb
require "digest"
module UsersHelper
  def gravatar_for user, size: Settings.avatar.size
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/tours/_tour.html.erb
<tr>
  <td><%= tour.id %></td>
  <td><%= tour.name %></td>
  <td><%= tour.start_palace %></td>
  <td><%= tour.end_palace %></td>
  <td><%= tour.transport %></td>
  <td><%= tour.quantity %></td>
  <td>
    <%= link_to t("admin.update"), edit_admin_tour_path(tour) %>
    |
    <%=link_to t("admin.delete"), admin_tours_path(tour), method: :delete %>
  </td>
</tr>

app/views/admin/tours/edit.html.erb
<div class="row">
  <div class="col-md6 col-md-offset-3">
    <%= form_for(@tour, url: admin_tour_index_path) do |f| %>

      <%= f.label t "admin.users.edit.name" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label t "admin.users.edit.email" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label t "admin.users.edit.password" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label t "admin.users.edit.confirm_password" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("admin.update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<% provide :title, t("admin.destination") %>
<body>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= t("admin.destination") %></h1>
    </div>
  </div>
  <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="btn-group">
      <div class="row">
        <div class="navbar-form navbar-right">
          <%= form_tag admin_tours_path do %>
            <%= label_tag :name %>
            <%= text_field_tag :name %>
            <%= submit_tag t("admin.review.search"), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t("tour.route") %></th>
            <th><%= t("tour.time") %></th>
            <th><%= t("tour.start_palace") %></th>
            <th><%= t("tour.end_palace") %></th>
            <th><%= t("tour.transport") %></th>
            <th><%= t("tour.quantity") %></th>
            <th><%= t("admin.users.index.action") %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @tours %>
        </tbody>
        <%= will_paginate %>
      </table>
    </div>
  </div>
</body>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.gender %></td>
  <td><%= user.date_of_birth %></td>
  <td><%= user.address %></td>
  <td><%= user.phone %></td>
  <td><%= user.role %></td>
  <td><%=link_to t("admin.user.delete"),
    admin_users_path(user), method: :delete %></td>
</tr>

app/views/admin/users/index.html.erb
<% provide :title, t("admin.user.title") %>
<body>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= t("admin.user.title") %></h1>
    </div>
  </div>
  <div>
    <div class="btn-group">
      <div class="row">
        <div class="search">
          <%= search_form_for @search, url: admin_users_path do |f| %>
          <%= f.label :name_cont, t("admin.user_name") %>
          <%= f.search_field :name_cont, class: "form_label" %>
          <%= f.submit t("admin.review.search"), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t("admin.user.id") %></th>
            <th><%= t("admin.user.name") %></th>
            <th><%= t("admin.user.gendor") %></th>
            <th><%= t("admin.user.dob") %></th>
            <th><%= t("admin.user.address") %></th>
            <th><%= t("admin.user.phone") %></th>
            <th><%= t("admin.user.role") %></th>
            <th><%= t("admin.user.action") %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
        <%= will_paginate %>
      </table>
    </div>
  </div>
</body>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages" %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :date_of_birth %>
  <%= f.date_field :date_of_birth, class: "form-control" %>

  <%= f.label :gender %>
  <div id="gender-area">
    <%= f.label(:gender_0, t("user.male")) %>
    <%= f.radio_button(:gender, User.genders[:male]) %>
    <%= f.label(:gender_1, t("user.female")) %>
    <%= f.radio_button(:gender, User.genders[:female]) %>
  </div>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, t("user.edit")) %>
<% provide(:button_text, t("user.save")) %>
<h1><%= t "user.update_profile" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t "user.change" %></a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, t("user.sign_up")) %>
<% provide(:button_text, t("user.btntext")) %>
<h1><%= t("user.sign_up") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= t("user.profile") %></h1>
<div class="profile">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
        <div class="date">
          <tr>
            <td><%= t("user.date_birth") %></td>
            <td><%= l @user.date_of_birth, format: :long %></td>
          </tr>
        </div>
        <div class="info">
          <tr>
            <td><%= t("user.email") %></td>
            <td><%= @user.email %></td>
          </tr>
        </div>
        <div class="info">
          <tr>
            <td><%= t("user.gender") %></td>
            <td><%= @user.gender %></td>
          </tr>
        </div>
        <div class="info">
          <tr>
            <td><%= t("user.address") %></td>
            <td><%= @user.address %></td>
          </tr>
        </div>
        <div class="info">
          <tr>
            <td><%= t("user.phone") %></td>
            <td><%= @user.phone %></td>
          </tr>
        </div>
      </section>
    </aside>
  </div>
</div>