config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  namespace :admin do
    root "static_pages#index"
    resources :reviews
    resources :users
    resources :tours
  end
  resources :tours do
    resources :comments
  end
  resources :book_tours
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
      if user.admin?
        can :manage, :all
      else
        can :read, [User, Tour]
        can :update, User, id: user.id
        can [:create, :read], [BookTour, Comment, Rating]
        can :destory, Comment do |comment|
          comment.user == user
        end
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :tour
  belongs_to :user

  validate :check_valid_tour

  def check_valid_tour
    if quantity == nil
      errors.add(:quantity, Settings.book_tour.quantity_nil)
    elsif sum_quantity < quantity
      errors.add(:quantity, quantity.to_s + Settings.book_tour.quantity_cant)
    end
  end

  def sum_quantity
    tour.quantity - tour.book_tours.sum(:quantity)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tours
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  scope :newest, ->{order :created_at}
  delegate :name, to: :user
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_and_belongs_to_many :tours
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :tour
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_and_belongs_to_many :hotels
  belongs_to :category
  has_many :ratings
  has_many :comments
  has_many :book_tours

  scope :destination_tour,
    ->{where category_id: Settings.admin.destination_tour}
  scope :newest, ->{order :created_at}
  scope :order_name, ->{order :name}
end

app/models/tours_hotel.rb
class ToursHotel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :book_tours
  enum role: {user: 0, admin: 1}
  enum gender: {male: 0, female: 1}

  scope :newest, ->{order :created_at}
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  def index
    @tours = Tour.destination_tour.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @search = User.ransack params[:q]
    @users = @search.result.newest.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:name, :date_of_birth, :gender, :address, :phone])
  end
end

app/controllers/book_tours_controller.rb
class BookToursController < ApplicationController
  before_action :load_tour, only: :show
  before_action :load_tour_for_create, only: :create

  def create
    @book_tour = BookTour.new tour_params
    if @book_tour.save
      flash[:success] = t "messenger.success_tour"
      redirect_to tours_path
    else
      flash[:danger] = t "messenger.book_fails"
      render :template => "book_tours/show"
    end
  end

  def show
    @book_tour = BookTour.new
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    redirect_to tours_path
  end

  def load_tour_for_create
    @tour = Tour.find_by id: params[:book_tour][:tour_id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    redirect_to tours_path
  end

  def tour_params
    params.require(:book_tour).permit :user_id, :tour_id, :quantity,
      :price, :note
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_comment, only: :destroy

  def create
    @comment = Comment.new comment_params
    if @comment.save
      flash[:success] = t "comment.successful"
      redirect_to tour_path @comment.tour_id
    else
      flash[:danger] = t "comment.fails"
      redirect_to tour_path @comment.tour_id
    end
  end

  def destroy
    if @comment.destroy
      flash[:success] = t "comment.delete"
      redirect_to tour_path @comment.tour_id
    else
      flash[:danger] = t "comment.fails"
      redirect_to tour_path @comment.tour_id
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content, :user_id, :tour_id
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    return if @comment
    flash[:danger] = t "messenger.no_data"
    redirect_to tour_path @comment.tour_id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @search = Tour.ransack params[:q]
    @tours = @search.result.order_name.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :load_tour, only: %i(show load_status)
  authorize_resource

  def index
    @search = Tour.ransack params[:q]
    @tours = @search.result.newest.paginate page: params[:page],
      per_page: Settings.tour.per_page
  end

  def show
    @status = load_status
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_status
    quantity = @tour.book_tours.sum :quantity
    @tour.quantity - quantity
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(show edit update)

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.gender = params[:gender].to_i
    if @user.save
      log_in @user
      flash[:success] = t "welcome"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @user.gender = params[:gender].to_i
    if @user.update_attributes user_params
      flash[:success] = t "user.update"
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "messenger.no_data"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit :name, :email, :date_of_birth,
      :address, :phone, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include TourHelper
  def full_title page_title
    base_title = I18n.t "framgia.base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/tour_helper.rb
module TourHelper
  def route content
    return if content.length <= Settings.tour.length_small
    truncate content, length: Settings.tour.length_big
  end
end

app/helpers/users_helper.rb
require "digest"
module UsersHelper
  def gravatar_for user, size: Settings.avatar.size
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/book_tours/_tour.html.erb
<div class="col-md-4 ftco-animate">
  <div class="destination">
    <a class="img img-2 d-flex justify-content-center align-items-center" style="background-image: url(<%= tour.image %>);">
      <div class="icon d-flex justify-content-center align-items-center">
      </div>
    </a>
    <div class="text p-3">
      <div class="d-flex">
        <div class="one">
          <h3>
            <%= link_to tour.name, tour %>
          </h3>
        </div>
        <div class="two">
          <span class="price">
            <%= t("dola") %><%= tour.price %>
          </span>
        </div>
      </div>
      <p>
        <%= route(tour.route) %>
      </p>
      <p class="days"><span><%= tour.start_tour.strftime t("tour.fomat_date") %><%= t("to")%>
        <%= tour.end_tour.strftime t("tour.fomat_date") %></span></p>
      <hr>
      <p class="bottom-area d-flex">
        <span><i class="icon-map-o"></i><%= tour.category.name %></span>
        <% @tours.each do |book| %>
          <%= link_to t("book_tour.delete"), book, method: :delete,
            data: { confirm: t("book_tour.you_sure")} %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/book_tours/index.html.erb
<% provide(:title, 'tour') %>
<h1>tour</h1>

<ul class="tours">
    <%= render partial: "book_tours/tour", collection: @tours %>
</ul>
<%= will_paginate @tours %>

app/views/book_tours/show.html.erb
<div class="product-corporate-main offset-top">
  <h2><%= t("tour_infor") %></h2>
  <table class="product-corporate-book">
    <tbody>
    <tr>
      <td><%= t("book_tour.customer_name") %></td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.address") %></td>
      <td><%= current_user.address %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.phone") %></td>
      <td><%= current_user.phone %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.gender") %></td>
      <td><%= current_user.gender %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.date_birth") %></td>
      <td><%= current_user.date_of_birth.
        strftime t("tour.fomat_date") %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.name_tour") %></td>
      <td><%= @tour.name %></td>
    </tr>
    <tr>
      <td><%= t("book_tour.price") %></td>
      <td><%= @tour.price %><%= t("dola")%></td>
    </tr>
    <tr>
      <td><%= t("tour.time") %></td>
      <td><%= @tour.start_tour.strftime t("tour.fomat_date") %><%= t("to") %>
    <%= @tour.end_tour.strftime t("tour.fomat_date") %></td>
    </tr>
    <tr>
      <td><%= t("tour.start_palace") %></td>
      <td><%= @tour.start_palace %></td>
    </tr>
    <tr>
      <td><%= t("tour.end_palace") %></td>
      <td><%= @tour.end_palace %></td>
    </tr>
    <tr>
      <td><%= t("tour.transport") %></td>
      <td><%= @tour.transport %></td>
    </tr>
    <tr>
      <td><%= t("tour.category") %></td>
      <td><%= @tour.category.name %></td>
    </tr>
    </tbody>
  </table>
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@book_tour, url: book_tours_path) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :tour_id, value: @tour.id %>
      <%= f.hidden_field :price, value: @tour.price %>
      <%= f.label t("book_tour.quantity") %>
      <%= f.number_field :quantity, class: "form-control",
        min: Settings.book_tour.min_quantity,
        max: Settings.book_tour.max_quantity %>
      <%= f.label t("book_tour.note") %>
      <%= f.text_field :note, class: "form-control" %>
      <%= f.submit t("tour.book_tour"),
        class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
  </form>
</div>

app/views/comments/_comment.html.erb
<%= t"comment.name" %><%= comment.name %>
<br>
<%= t"comment.content" %><%= comment.content %>
<br>
<%= time_ago_in_words(comment.created_at) %>
<br>
<% if can? :destory, comment %>
  <%= link_to "delete", [comment.tour, comment], method: :delete,
    data: { confirm: t("comment.you_sure") } %>
<% end %>
<br>
<br>

app/views/comments/_form.html.erb
<%= form_for @tour.comments.build, url: tour_comments_path(@tour),
  method: :post do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :tour_id, value: @tour.id %>
  <%= f.label t "comment.contents" %>
  <%= f.text_field :content, class: "form-control" %>
  <%= f.submit t("comment.add"), class: "btn btn-lg btn-primary" %>
<% end %>